# Generated by Django 2.2 on 2019-06-17 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('busapp', '0002_auto_20190615_1119'),
    ]

    operations = [
        migrations.RenameField(
            model_name='elite',
            old_name='destination',
            new_name='Destination',
        ),
        migrations.RenameField(
            model_name='elite',
            old_name='source',
            new_name='Source',
        ),
        migrations.RenameField(
            model_name='normal',
            old_name='destination',
            new_name='Destination',
        ),
        migrations.RenameField(
            model_name='normal',
            old_name='source',
            new_name='Source',
        ),
        migrations.RenameField(
            model_name='premium',
            old_name='destination',
            new_name='Destination',
        ),
        migrations.RenameField(
            model_name='premium',
            old_name='source',
            new_name='Source',
        ),
    ]
